openapi: 3.1.0
info:
  title: Verification Code Management API
  description: |
    This API manages verification codes for various verification scenarios, including validation and resending.
  version: 1.0.0
servers:
  - url: https://{serverUrl}/t/{tenantDomain}/api/identity/user/v1.0
    variables:
      serverUrl:
        default: localhost:9443
      tenantDomain:
        default: carbon.super
security:
  - OAuth2: []
  - BasicAuth: []
paths:
  /validate-code:
    post:
      tags:
        - Verification Code
      summary: Validate code
      description: |
        This API is used to validate the code generated during the verification process associated with a user.

        <b>Scope(Permission) required:</b> `internal_user_code_mgt_create`
      operationId: validateCode
      requestBody:
        description: The validation code retrieved for the verification scenario, and optional property parameters.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeValidationRequest'
      responses:
        '202':
          description: Accepted
          content: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X POST \
            -H "Authorization: Basic YWRtaW46YWRtaW4=" \
            -H "Content-Type: application/json" \
            -d '{
              "code": "string",
              "properties": []
            }' \
            "https://localhost:9443/api/identity/user/v1.0/validate-code"
  /resend-code:
    post:
      tags:
        - Verification Code
      summary: Resend code
      description: |
        This API is used to resend the confirmation code if it is missing.

        <b>Scope(Permission) required:</b> `internal_user_code_mgt_create`
      operationId: resendCode
      requestBody:
        description: User information and optional property parameters to resend the verification code.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendCodeRequest'
      responses:
        '201':
          description: Created
          content: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X POST \
            -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
            -H 'Content-Type: application/json' \
            -d '{
              "user": {
                "username": "string",
                "realm": "string"
              },
              "properties": [
                {
                  "key": "string",
                  "value": "string"
                }
              ]
            }' \
            'https://localhost:9443/api/identity/user/v1.0/resend-code'
components:
  schemas:
    CodeValidationRequest:
      type: object
      properties:
        code:
          type: string
        properties:
          type: array
          items:
            $ref: '#/components/schemas/Property'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string
        traceId:
          type: string
    Property:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ResendCodeRequest:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        properties:
          type: array
          items:
            $ref: '#/components/schemas/Property'
    User:
      type: object
      properties:
        username:
          type: string
        realm:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://localhost:9443/oauth2/authorize'
          tokenUrl: 'https://localhost:9443/oauth2/token'
          scopes: {
            internal_user_code_mgt_create: Grant create access to user code management in the organization (root)
          }
